// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oejlmxsdjztzahlawdwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lamxteHNkanp0emFobGF3ZHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjQzNDIsImV4cCI6MjA2MDU0MDM0Mn0.aFN770tKK3qJU9hVT_zewsnyy9nX0KyORn_Hy0BLPuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);